viest/php-ext-xlswriter

README.md
excel_writer.c
kernel/excel.c
kernel/format.c
kernel/include.h
php_excel_writer.h

```php
$config = [
'path' => './tests'
];
$excel = new \Vtiful\Kernel\Excel($config);
$fileFd = $excel->fileName('tutorial01.xlsx');
// End here
```

 FIX(memory): Process end, but not output file, memory leak.

---

.gitignore
tests/005.phpt
tests/010.phpt
tests/011.phpt
tests/012.phpt
tests/013.phpt
tests/014.phpt
tests/015.phpt
tests/016.phpt

add CLEAN sections to tests, and ignore build artefacts

---

kernel/excel.c
kernel/include.h
php_xls_writer.h
tests/018.phpt

* Data Bulk Insert automatic maintenance line number.
* Customizing the default sheet name.

 FEAT: Incremental add with default sheet name

---

config.m4
kernel/excel.c
kernel/format.c
kernel/include.h
kernel/write.c

Changelog: https://github.com/jmcnamara/libxlsxwriter/blob/master/Changes.txt
ABI compliance checker: https://rpms.remirepo.net/compat_reports/libxlsxwriter/0.7.9_to_0.8.0/compat_report.html

fix for libxlsxwriter 0.8.0

---

config.w32
tests/001.phpt
tests/002.phpt
tests/003.phpt
tests/004.phpt
tests/005.phpt
tests/006.phpt
tests/007.phpt
tests/008.phpt
tests/009.phpt
tests/010.phpt
tests/011.phpt
tests/012.phpt
travis/run-test.sh

Hello, this patch trims some trailing whitespace across the source code files and tests.
Thanks.

Trim trailing whitespace

---

README_zh.md
kernel/excel.c
kernel/format.c
kernel/include.h
kernel/write.c
tests/007.phpt
tests/008.phpt
tests/009.phpt
tests/011.phpt
tests/012.phpt
tests/format_align.phpt
tests/image_no_styles.phpt
tests/image_width_height_styles.phpt

* Format: multiple style overlays
* Image: width and height scale

Feat Format And Image

---

config.m4

add library default build options

---

include/xlswriter.h
kernel/excel.c
kernel/write.c
tests/insert_text_resource_format.phpt

Reverts viest/php-ext-excel-export#130

Feat(insertText): support resource format

---

kernel/read.c

fix stack mashing using proper format

---

ide-helper/helper.php
include/xlswriter.h
kernel/excel.c
kernel/format.c
kernel/write.c
package.xml
tests/format_background.phpt
tests/format_font.phpt
tests/freeze_panes.phpt

```php
freezePanes(int $row, int $column)
```

Merge dev branch

---

config.m4
kernel/write.c

see 
* https://rpms.remirepo.net/compat_reports/libxlsxwriter/0.8.7_to_0.8.8/compat_report.html
* https://github.com/jmcnamara/libxlsxwriter/commit/f360f75cd0979cb65031ac834d94eafd3897716b
With this patch
```
=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   15
---------------------------------------------------------------------
Number of tests :   66                66
Tests skipped   :    0 (  0.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Tests passed    :   66 (100.0%) (100.0%)
---------------------------------------------------------------------
Time taken      :    1 seconds …
```

fix compatibility with libxlsxwriter 0.8.8

---

package.xml
php_xlswriter.h

- FEAT display or hide screen and print gridlines.
- FEAT worksheet zoom.
- FEAT data method is written by default from the file header.
- FEAT returns null if the type is specified and the cell is empty.
- FEAT sheet list.
- FEAT xlsx to csv.

version 1.3.2

---

kernel/read.c
tests/fix-207.phpt
tests/open_xlsx_get_data_with_set_type.phpt

Fix: read: Turning data into custom types

---

include/csv.h
include/xlswriter.h
kernel/csv.c
kernel/excel.c
kernel/write.c
package.xml
tests/xlsx_to_csv_callback_custom_delimiter.phpt
tests/xlsx_to_csv_custom_delimiter.phpt

Feat: sheet writer exception and custom csv delimiter

---

.gitignore
include/excel.h
include/read.h
include/xlswriter.h
kernel/common.c
kernel/excel.c
kernel/read.c
kernel/write.c
package.xml
tests/open_xlsx_get_data_skip_rows.phpt
tests/open_xlsx_next_row_skip_rows.phpt
tests/xlsx_to_csv_skip_rows.phpt
tests/xlsx_to_csv_skip_rows_callback.phpt

- skip rows;
- timestamp using php global timezone;
- insertDate using php global timezone;

Feat: reader, writer

---

kernel/write.c

See https://rpms.remirepo.net/compat_reports/libxlsxwriter/0.9.1_to_0.9.3/compat_report.html
Notice, `LXW_VERSION_ID` make such changes easier (than using config.m4), perhaps will make sense, to upgrade bundled library to a recent version with this version, and cleanup sources.

fix build with libxlsxwriter-0.9.3

---

.gitignore
kernel/read.c

Fix: musl libc

---

config.m4
config.w32
include/help.h
include/xlswriter.h
kernel/excel.c
kernel/help.c
kernel/read.c
tests/timestamp_from_date_double.phpt

Feat: timestampFromDateDouble

---

kernel/common.c
kernel/excel.c

Fix: header line no and sheet checkout not init line no

---

include/csv.h
include/read.h
include/xlswriter.h
kernel/csv.c
kernel/excel.c
kernel/read.c
tests/open_xlsx_global_data_type.phpt

```php
$config   = ['path' => './tests'];
$excel    = new \Vtiful\Kernel\Excel($config);
$filePath = $excel->fileName('tutorial.xlsx')
->header(['Item', 'Cost', 'Int', 'Double'])
->data([
['Item_1', 'Cost_1', 10, 10.9999995],
])
->output();
$data = $excel->openFile('tutorial.xlsx')
->openSheet()
->setGlobalType(\Vtiful\Kernel\Excel::TYPE_STRING)
->getSheetData();
var_dump($data);
```
output
```
array(2) {
[0]=>
array(4) {
[0]=>
string(4) "Item"
[1]=>
string(4) "Cost"
[2]=>
string(3) "Int"
[3]=>
string(6) "Double"
}
[1]=>
array(4) {
[0]=>
string(6) "Item_1"
[1]=>
string(6) "Cost_1"
[2]=>
string(2) "10"
[3]=>
string(10) "10.9999995"
}
}
```

Feat: set global type

---

.appveyor.yml
kernel/format.c
package.xml
tests/format_unlocked.phpt

Feat: unlock format

---

kernel/excel.c
kernel/resource.c
kernel/write.c
tests/insert_date_resource_format.phpt

Fix(kernel): insertDate use curtom format segmentation fault

---

config.m4
include/exception.h
include/xlswriter.h
kernel/csv.c
kernel/excel.c
kernel/exception.c
kernel/help.c
tests/writer_exception.phpt

1. default enable reader
2. exception message
3. fix #375

exception message, reader, PHP8.1

---

.travis.yml
config.m4
config.w32
include/rich_string.h
include/xlswriter.h
kernel/excel.c
kernel/format.c
kernel/resource.c
kernel/rich_string.c
kernel/write.c
package.xml
tests/rich_string.phpt
xlswriter.c

```php
$config = ['path' => './tests'];
$fileObject = new \Vtiful\Kernel\Excel($config);
$fileObject = $fileObject->fileName("rich_string.xlsx")
->header(['rick string']);
$fileHandle = $fileObject->getHandle();
$format1   = new \Vtiful\Kernel\Format($fileHandle);
$colorRed = $format1->fontColor(\Vtiful\Kernel\Format::COLOR_GREEN)->toResource();
$format2      = new \Vtiful\Kernel\Format($fileHandle);
$colorOrange = $format2->fontColor(\Vtiful\Kernel\Format::COLOR_ORANGE)->toResource();
$richStringOne = new \Vtiful\Kernel\RichString('red ', $colorRed);
$richStringTwo = new \Vtiful\Kernel\RichString('orange', $colorOrange);
var_dump($richStringOne, $richStringTwo);
$fileObject->insertRichText(1, 0, [
$richStringOne,
$richStringTwo
]);
$fileObject->output();
```

Feat: rich string

---

.gitignore
kernel/read.c
kernel/write.c
tests/data_string_key.phpt
tests/open_xlsx_get_data_bignumbers.phpt

Feat(Read): big numbers

---

kernel/validation.c

Following PR #451
Encounter 2 failed tests with 8.2, also reported by another user on #469

Another fix for PACKED array on PHP 8.2

---

kernel/excel.c
tests/011.phpt
tests/012.phpt
tests/014.phpt
tests/016.phpt

fixes viest/php-ext-xlswriter#494

Fix pass explicit null to optional format argument

---

tests/open_xlsx_next_row_with_data_type_date_array_index.phpt

Need to switch back to official library
Behavior change discussed on https://github.com/brechtsanders/xlsxio/issues/75

fix test expectation with libxlsxio 0.2.28

---

include/help.h
include/xlswriter.h
kernel/excel.c
kernel/help.c
kernel/write.c
tests/outline_level_column.phpt
tests/outline_level_column_const_memory.phpt
tests/outline_level_row.phpt
tests/outline_level_row_const_memory.phpt
tests/validation_limiting_to_a_single_or_range_cell.phpt

Example on outline levels in libxlsxwriter: https://libxlsxwriter.github.io/working_with_outlines.html

Set outline level, collapsed/hidden options for rows/columns

---

kernel/format.c
tests/format_rotation.phpt

[Set the rotation of the text in a cell.](https://libxlsxwriter.github.io/format_8h.html#ae690004cd77f48646da07796b540c309)

Feat(Format): rotation

---

kernel/common.c

Update: format is empty in object_format

---

kernel/format.c
tests/format_indent.phpt

indent text in a cell
https://libxlsxwriter.github.io/format_8h.html#a99aea699cd7bb3c56a515c9c9e0caa69

Feat(Format): indent
